#!/usr/bin/env python

import scatter
import os
import sys


class Scatter_Capistrano(scatter.Scatter):
    def __init__(self, args):
        self.command = self.parse_args(args)
        super(Scatter_Capistrano, self).__init__(args)

    def parse_args(self, args):
        return ' '.join(args)


def scap():
    cap = Scatter_Capistrano(sys.argv[1:])
    deploy_dir = cap.get_deploy_dir()

    # Remove the first item, which is the script name
    if deploy_dir and cap.command:
        os.system("cd %s && cap %s" % (deploy_dir, cap.command))

if __name__ == '__main__':
    scap()
