#!/usr/bin/env python

import scatter
import os
import sys


class Scatter_Deploy(scatter.Scatter):
    def get_routines(self, deploy_dir):
        return {
            'custom': self.find_custom_deploy(deploy_dir),
            'capfile': self.find_capfile(deploy_dir)
        }

    def find_custom_deploy(self, path):
        # Deploy should be executable and named without a file extension
        deploy = path + 'deploy'
        return deploy if os.access(deploy, os.X_OK) else False


# Do it
deploy = Scatter_Deploy(sys.argv[1:])

deploy_dir = deploy.get_deploy_dir()
deploys = deploy.get_routines(deploy_dir)

# Check for a custom deploy script
if deploys['custom']:
    print 'Found deploy executable:', deploys['custom']
    os.system(deploys['custom'])

# Check for a Capfile
elif deploys['capfile']:
    print 'Found Capfile:', deploys['capfile']
    os.system("cd %s && cap deploy" % deploy_dir)

# Couldn't figure out what/how to deploy
else:
    sys.exit("Deploy fail :/")
