#!/usr/bin/env python

import scatter
import os
import sys


class Scatter_Deploy(scatter.Scatter):
    def get_routines(self, deploy_dir):
        custom = self.find_custom_deploy(deploy_dir)
        capfile = self.find_capfile(deploy_dir)

        return {'custom': custom, 'capfile': capfile}

    def find_custom_deploy(self, path):
        # Deploy should be executable and named without a file extension
        deploy = path + 'deploy'

        if not os.path.isfile(deploy):
            return False
        elif not os.access(deploy, os.X_OK):
            return False
        else:
            return deploy


# Do it
deploy = Scatter_Deploy()

deploy_dir = deploy.get_deploy_dir()
deploys = deploy.get_routines(deploy_dir)

# Check for a custom deploy script
if deploys['custom']:
    print 'Found deploy executable:', deploys['custom']
    os.system(deploys['custom'])

# Check for a Capfile
elif deploys['capfile']:
    print 'Found Capfile:', deploys['capfile']
    os.system('cd ' + deploy_dir + ' && cap deploy && cd -')

# Couldn't figure out what/how to deploy
else:
    sys.exit("Deploy fail :/")
